#!/bin/bash

export DOTFILES=$HOME/.dotfiles

ln -s $DOTFILES/.atom/*    $HOME/.atom
ln -s $DOTFILES/.gitconfig $HOME/.gitconfig
ln -s $DOTFILES/.aliases   $HOME/.aliases
ln -s $DOTFILES/.zshrc     $HOME/.zshrc
